language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
matrix:
  allow_failures:
  - python: 3.2
  - python: 3.3
  - python: 3.4
  - python: 3.5
  - python: 3.7-dev
install:
  - pip install flake8 codecov
before_script:
  - flake8 .
script: python setup.py nosetests
after_success:
  - codecov
